export default () => ({
  port: parseInt(process.env.PORT || '3000', 10),
  mongoUri: process.env.MONGODB_URI,
  jwtSecret: process.env.JWT_SECRET,
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || '7d',
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  googleCallbackUrl: process.env.GOOGLE_CALLBACK_URL,
  githubClientId: process.env.GITHUB_CLIENT_ID,
  githubClientSecret: process.env.GITHUB_CLIENT_SECRET,
  githubCallbackUrl: process.env.GITHUB_CALLBACK_URL,
  frontendUrl: process.env.FRONTEND_URL,
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN,
  telegramBotUsername: process.env.TELEGRAM_BOT_USERNAME,
  telegramWebhookSecret: process.env.TELEGRAM_WEBHOOK_SECRET,
  redisHost: process.env.REDIS_HOST || 'localhost',
  redisPort: parseInt(process.env.REDIS_PORT || '6379', 10),
  weatherApiBaseUrl: process.env.WEATHER_API_BASE_URL,
  defaultLatitude: parseFloat(process.env.DEFAULT_LATITUDE || '18.5204'),
  defaultLongitude: parseFloat(process.env.DEFAULT_LONGITUDE || '73.8567'),
  alertCronExpression: process.env.ALERT_CRON_EXPRESSION || '0 * * * *',
});
